create table if not exists public.task (
    id bigint generated by default as identity primary key,
    description text not null
);

insert into public.task (description)
values
    ('My test task'),
    ('My second test task');
